name: shortener_jenkins_stack

services:
  jenkins:
    build:
      context: .
      dockerfile: docker/jenkins/Dockerfile
    container_name: shortener_jenkins
    restart: unless-stopped
    user: root
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  jenkins_home: